version: '2.4'

services:
  auroral-agent:
    # image: auroral-agent
    image: registry.bavenir.eu/auroral_agent:dev
    volumes:
    - ./.env:/app/.env:ro
    - .:/app:delegated
    - ./agent:/app/agent
    depends_on:
      cache-db:
        condition: service_healthy
  proxy:
    restart: unless-stopped
    volumes:
    - ./nginx/logs:/var/log/nginx
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # - /etc/ssl/bavenir/bavenir_eu.key:/var/certificates/privkey.pem:ro
    # - /etc/ssl/bavenir/bavenir_eu.crt:/var/certificates/fullchain.pem:ro
    depends_on:
      cache-db:
        condition: service_healthy
    ports:
      - '${EXTERNAL_PORT}:80'
      # - 9997:9997
      # - 443:443
    image: nginx:stable
  gateway:
    # restart: unless-stopped
    volumes:
    - ./gateway/log:/gateway/log
    - ./gateway/data:/gateway/data
    - ./gateway/GatewayConfig.xml:/gateway/config/GatewayConfig.xml:ro
    - ./gateway/keystore:/gateway/keystore
    environment:
    - UID=9999
    - GID=9999
    # ports:
    # - 5222:5222
    image: registry.bavenir.eu/auroral_gateway:dev
    # image: auroral-gateway
  cache-db:
    # restart: unless-stopped
    # ports:
    # - 6379:6379
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
    - /usr/local/etc/redis/redis.conf
    image: redis:buster
  # helio:
  #   image: acimmino/helio-publisher:latest
  #   ports:
  #     - '9999:9999'
  #   volumes:
  #   - ./mapping:/helio/mapping
  #   - ./helio-storage:/helio/helio-storage
  triplestore:
    image: acimmino/auroral-fuseky:latest
    volumes:
      - triplestore:/fuseki
    # ports:
    #   - '3030:3030'
  wothive:
    image: acimmino/wot-hive:latest
    # volumes:
    #   - ./wothive/configuration.json:/usr/src/wothive/configuration.json
    # ports:
    #   - '9000:9000'
volumes:
    triplestore:
        external: true
